apiVersion: v1
kind: Namespace
metadata:
  name: intervue
  labels:
    app.kubernetes.io/name: intervue
---
apiVersion: v1
kind: Namespace
metadata:
  name: intervue-staging
  labels:
    app.kubernetes.io/name: intervue
    environment: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: intervue-production
  labels:
    app.kubernetes.io/name: intervue
    environment: production
